### ISSUE TITLE
Adaugă o licență

### ISSUE THREAD

**Issue by Secret-chest** [KiloProjects/Kilonova#17]
Ar trebui permisiunea tuturor contribuitorilor, dar văd că sunt doar doi.

Dacă ar fi alegerea mea, aș folosi AGPL.

**Comment by AlexVasiluta** [comment]
Cred ca @ezluci ar fi ok oricum am alege

Sincer, eu de cand zic ca pun licenta dezbat fie AGPL, fie MIT, nu stiu exact care ar fi decursul cel mai potrivit tbh :))

**Comment by Secret-chest** [comment]
Am și editat!!! Am uitat de AGPL!

Consider că e important să nu facă unele firme produs closed-source din Kilonova.

**Comment by Secret-chest** [comment]
Oricum, să nu punem licență non-comercială și la cod. La conținut are sens, la cod nu are.
