### ISSUE TITLE
Suport de Free Pascal

### ISSUE THREAD

**Issue by stalecu** [KiloProjects/Kilonova#18]
Salut! În primul rînd, vreau să te felicit pentru website, e ce-am căutat dintotdeauna la un site de probleme în România. Ah, și faptul că ai C++20 (🙏🏼) în loc de hardcode la C++11 cum face Silviu™.

Cu toate astea fiind zise, titlul este destul de explicit. Chiar dacă știu C++20, în mare parte tot prefer să folosesc Free Pascal (și mulți elevi încă fac Pascal, din {fericire, păcate}). Suportul pentru Free Pascal ar fi util în acest caz.

Comanda de compilare este la fel de simplă ca pe C++: `fpc -O2 -Xs nume.pas`. 

Sidenote: asta ar putea deschide posibilitatea la a adăuga mai multe limbaje de programare în viitor, dacă permite infrastructura ta (ar fi fain să adaugi Go, dacă tot rulezi tot prin Go).

Dacă ești de acord, pot să încep să fac un PR în acest sens.

**Comment by AlexVasiluta** [comment]
Hey.

O să adaug suport si pentru fpc, sa vad ce e disponibil in ubuntu repos. Am adaugat definitiile pt Go acum ceva vreme, dar am dezactivat manual fiindca niste modificari la toolchain l-au facut sa nu mai compileze. Mă ocup eu de modificari
