### ISSUE TITLE
Subtitlurile enunțurilor (cerință, date de intrare, date de ieșire etc.) sunt greșite

### ISSUE THREAD

**Issue by Secret-chest** [KiloProjects/Kilonova#20]
Ar trebui să fie H2, nu H1. Conform standardului HTML fiecare pagină ar trebui să aibă doar un H1.

**Comment by AlexVasiluta** [comment]
Poti sa arati exact unde cere sa fie un singur h1?

**Comment by Secret-chest** [comment]
Pe pagina enunțului sunt mai multe.

**Comment by Secret-chest** [comment]
Nu scrie, dar scrie că `h1` începe documentul.

**Comment by overanalytcl** [comment]
@AlexVasiluta 

@Secret-chest are dreptate:
- https://accessibility.psu.edu/headingshtml/ 
- https://webaim.org/techniques/semanticstructure/#headings (WebAIM = Web Accessibility in Mind)
- https://www.a11yproject.com/posts/how-to-accessible-heading-structure/ 

Problema acum este ca WCAG 2.1 AA (standardul urmat de obicei pentru a11y pe net, desi daca se poate AAA, si mai bine) nu considera o violare sa folosesti mai multe `h1`, dar e o practica foarte proasta. Ideea e ca s-a introdus HTML Document Outline in HTML5, dar nu au fost luate deloc in considerare tehnologiile asistive (e.g. cititoare de ecran) in seama si nici macar browserele nu au adoptat asta, deci suportul pentru mai multe `<h1>`-uri s-a scos in HTML5.1. Chiar recomand sa citesti astea:
- https://html5doctor.com/computer-says-no-to-html5-document-outline/
- https://codepen.io/stevef/post/a-decade-of-heading-backwards
- https://adrianroselli.com/2016/08/there-is-no-document-outline-algorithm.html

h1 ar trebui sa ai doar pentru titlul la o problema si restul sa fie h2. Exemplu de pagina este: https://kilonova.ro/problems/2638?list_id=1072, unde ai h1 la "Cerinta", "Date de intrare" s.a.m.d. Sa o pun in termeni de LaTeX (la un article, cel putin, ca doar nu scrii carti sau rapoarte), h1 = \title, h2 = \section etc. Cum nu ai mai multe \title-uri in LaTeX, nici tu n-ar trebui sa poti avea mai mult de un h1.

O sa pun un issue separat despre a11y, ca sa nu mai lungesc aici (si am mai multe de spus).
